FROM python:3.9-slim

WORKDIR /app
COPY . .
RUN pip install --upgrade pip && \
    pip install -r src/requirements.txt && \
    pip install -e .

EXPOSE 8501
ENTRYPOINT ["streamlit", "run", "src/app.py"]
